In [9]:
import socket
import cv2
import numpy as np

In [14]:
for i in range(5):
    soc = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    soc.connect((socket.gethostname(),1234))
    message = soc.recv(1024)
    print(message.decode("utf-8"))
    img = message.decode("utf-8")
    #cv2.imshow('did it?',message.decode("utf-8"))

[[[245 231 202]
  [244 230 201]
  [244 230 201]
  ...
  [235 181  94]
  [235 181  94]
  [235 181  94]]

 [[245 231 202]
  [244 230 201]
  [244 230 201]
  ...
  [234 181  94]
  [234 181  94]
  [234 181  94]]

 [[245 231 202]
  [244 230 201]
  [244 230 201]
  ...
  [234 180  95]
  [234 180  95]
  [234 180  95]]

 ...

 [[ 68  42  26]
  [ 66  40  24]
  [ 65  39  23]
  ...
  [ 41  53  57]
  [ 43  55  59]
  [ 37  49  53]]

 [[ 69  42  28]
  [ 67  40  26]
  [ 66  39  25]
  ...
  [ 30  42  44]
  [ 33  42  45]
  [ 32  41  44]]

 [[ 69  42  28]
  [ 68  41  27]
  [ 67  40  26]
  ...
  [ 28  36  35]
  [ 26  34  33]
  [ 29  34  35]]]
[[[245 231 202]
  [244 230 201]
  [244 230 201]
  ...
  [235 181  94]
  [235 181  94]
  [235 181  94]]

 [[245 231 202]
  [244 230 201]
  [244 230 201]
  ...
  [234 181  94]
  [234 181  94]
  [234 181  94]]

 [[245 231 202]
  [244 230 201]
  [244 230 201]
  ...
  [234 180  95]
  [234 180  95]
  [234 180  95]]

 ...

 [[ 68  42  26]
  [ 66  40  24]
  [ 65  39  23]
  ..

In [15]:
soc = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
soc.connect((socket.gethostname(),1234))
message = soc.recv(1024)
#print(message.decode("utf-8"))
img = message.decode("utf-8")

#cv2.imshow('did it?',message.decode("utf-8"))

[[[245 231 202]
  [244 230 201]
  [244 230 201]
  ...
  [235 181  94]
  [235 181  94]
  [235 181  94]]

 [[245 231 202]
  [244 230 201]
  [244 230 201]
  ...
  [234 181  94]
  [234 181  94]
  [234 181  94]]

 [[245 231 202]
  [244 230 201]
  [244 230 201]
  ...
  [234 180  95]
  [234 180  95]
  [234 180  95]]

 ...

 [[ 68  42  26]
  [ 66  40  24]
  [ 65  39  23]
  ...
  [ 41  53  57]
  [ 43  55  59]
  [ 37  49  53]]

 [[ 69  42  28]
  [ 67  40  26]
  [ 66  39  25]
  ...
  [ 30  42  44]
  [ 33  42  45]
  [ 32  41  44]]

 [[ 69  42  28]
  [ 68  41  27]
  [ 67  40  26]
  ...
  [ 28  36  35]
  [ 26  34  33]
  [ 29  34  35]]]


In [18]:
cv2.imshow('vice',np.uint8(img))
cv2.waitKey(0)
cv2.destroyAllWindows()

ValueError: invalid literal for int() with base 10: '[[[245 231 202]\n  [244 230 201]\n  [244 230 201]\n  ...\n  [235 181  94]\n  [235 181  94]\n  [235 181  94]]\n\n [[245 231 202]\n  [244 230 201]\n  [244 230 201]\n  ...\n  [234 181  94]\n  [234 181  